USE [GrReporting]
GO

IF NOT EXISTS(Select * From INFORMATION_SCHEMA.TABLES Where TABLE_NAME = 'AdditionalValidCombinationsForOriginatingSubRegionFunctionalDepartment')
	BEGIN
	CREATE TABLE [dbo].[AdditionalValidCombinationsForOriginatingSubRegionFunctionalDepartment](
		[OriginatingSubRegionName] [varchar](50) NOT NULL,
		[FunctionalDepartmentName] [varchar](100) NOT NULL
	) ON [PRIMARY]
	
	CREATE UNIQUE NONCLUSTERED INDEX [IX_Unique] ON [dbo].[AdditionalValidCombinationsForOriginatingSubRegionFunctionalDepartment] 
	(
		[OriginatingSubRegionName] ASC,
		[FunctionalDepartmentName] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

	END
GO

IF NOT EXISTS(Select * From INFORMATION_SCHEMA.TABLES Where TABLE_NAME = 'AdditionalValidCombinationsForEntityActivity')
	BEGIN
	CREATE TABLE [dbo].[AdditionalValidCombinationsForEntityActivity](
		[ReportingEntityName] [varchar](100) NOT NULL,
		[ActivityTypeName] [varchar](50) NOT NULL,
		[AllocationTypeName] [varchar](10) NOT NULL
	) ON [PRIMARY]

	CREATE UNIQUE NONCLUSTERED INDEX [IX_Unique] ON [dbo].[AdditionalValidCombinationsForEntityActivity] 
	(
		[ReportingEntityName] ASC,
		[ActivityTypeName] ASC,
		[AllocationTypeName] ASC
	)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]

	END
GO

DELETE From AdditionalValidCombinationsForOriginatingSubRegionFunctionalDepartment
DELETE From AdditionalValidCombinationsForEntityActivity

Insert Into AdditionalValidCombinationsForOriginatingSubRegionFunctionalDepartment (OriginatingSubRegionName,FunctionalDepartmentName)VALUES('Australia','Accounting')
Insert Into AdditionalValidCombinationsForOriginatingSubRegionFunctionalDepartment (OriginatingSubRegionName,FunctionalDepartmentName)VALUES('Australia','Information Technology')
Insert Into AdditionalValidCombinationsForOriginatingSubRegionFunctionalDepartment (OriginatingSubRegionName,FunctionalDepartmentName)VALUES('Australia','Portfolio Management')
Insert Into AdditionalValidCombinationsForOriginatingSubRegionFunctionalDepartment (OriginatingSubRegionName,FunctionalDepartmentName)VALUES('Australia','Tax')

GO
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('10/30 S. Wacker','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('10/30 S. Wacker','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('10/30 S. Wacker','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('10/30 S. Wacker','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('10/30 S. Wacker','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('1717 Penn Ave-Corp Entity','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('1717 Penn Ave-Corp Entity','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('201 Folsom','Development','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('201 Folsom','Development','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('4000 Macarthur JV','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('4000 Macarthur JV','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('666 5th Avenue (SOLD)','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('666 5th Avenue (SOLD)','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('666 5th Avenue (SOLD)','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('666 5th Avenue (SOLD)','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('666 5th Avenue (SOLD)','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Bayside Towers III','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Bayside Towers III','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Bayside Towers III','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Bayside Towers III','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Bayside Towers-Corp Entity','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Bayside Towers-Corp Entity','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('BEA Site','Development','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('BEA Site','Development','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Bond Building-Corp Entity','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Bond Building-Corp Entity','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Brazil Fund III_GP','Asset Management','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Brazil Fund III_GP','Asset Management','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Canal Center','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Canal Center','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Canal Center','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Canal Center','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Canal Center','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Canal Center 44 - Corp Entity','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Canal Center 44 - Corp Entity','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('CBX','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('CBX','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('CBX','Property Management CapEx','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('CBX','Property Management TI','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('CBX','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('CBX','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('CBX','Property Management CapEx','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('CBX','Property Management TI','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Clark','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Clark','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Clark','Property Management CapEx','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Clark','Property Management TI','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Clark','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Clark','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Clark','Property Management CapEx','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Clark','Property Management TI','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Colony Square','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Colony Square','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Colony Square','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Colony Square','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Colony Square','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Courvoisier Center','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Courvoisier Center','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Courvoisier Center','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Courvoisier Center','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Dublin Corp Center','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Dublin Corp Center','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Dublin Corp Center','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Dublin Corp Center','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Dublin Corp Center','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Dublin Corp Ctr-Corp Ent','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Dublin Corp Ctr-Corp Ent','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Friedrichstrasse 205','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Friedrichstrasse 205','Property Management CapEx','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Friedrichstrasse 205','Property Management CapEx','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Friedrichstrasse 205','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Friedrichstrasse 205','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Friedrichstrasse 205','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Friedrichstrasse 205','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Friedrichstrasse 205','Property Management TI','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Friedrichstrasse 205','Property Management TI','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Fund I Extension_Fund GP','Asset Management','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Fund I Extension_Fund GP','Asset Management','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Fund VIII_LP','Acquisitions','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Fund VIII_LP','Asset Management','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Fund VIII_LP','Fund Operations','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Fund VIII_LP','Fund Operations','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Hearst Tower','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Hearst Tower','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Hearst Tower','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Hearst Tower','Property Management TI','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('HTC 0','Asset Management','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('HTC 0','Asset Management','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('HTC 0','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('HTC 0','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Imperial Promenade','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Imperial Promenade','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Imperial Promenade','Property Management CapEx','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Imperial Promenade','Property Management TI','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Imperial Promenade','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Imperial Promenade','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Imperial Promenade','Property Management CapEx','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Imperial Promenade','Property Management TI','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('India Fund II_GP','Asset Management','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('India Fund II_GP','Asset Management','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('International Square','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('International Square','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('International Square','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('International Square','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('International Square','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Interstate North complex','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Interstate North complex','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Interstate North complex','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Interstate North complex','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Interstate North complex','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Lakeside complex','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Lakeside complex','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Lakeside complex','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Lakeside complex','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Lakeside complex','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Le Copernic','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Le Copernic','Property Management CapEx','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Le Copernic','Property Management CapEx','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Le Copernic','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Le Copernic','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Le Copernic','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Le Copernic','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Lehman Data Center','Development','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Lehman Data Center','Development','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('London Core Club','Acquisitions','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('London Core Club','Asset Management','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('London Core Club','Fund Organization','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('London Core Club','Fund Operations','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('London Core Club','Syndication (Investment and Fund)','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('London Core Club','Acquisitions','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('London Core Club','Asset Management','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('London Core Club','Fund Organization','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('London Core Club','Fund Operations','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('London Core Club','Syndication (Investment and Fund)','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('MetroPark','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('MetroPark','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('MetroPark','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('MetroPark','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('MetroPark','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Midtown Plaza','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Midtown Plaza','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Midtown Plaza','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Midtown Plaza','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Midtown Plaza','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Newseum Development','Development','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Newseum Development','Development','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Peterborough Court','Development','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Peterborough Court','Development','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Port Authority','Development','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Port Authority','Development','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Project Motorcycle_Fund GP','Asset Management','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Project Motorcycle_Fund GP','Asset Management','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Project Peach','Asset Management','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Project Peach','Asset Management','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('RC Holdco','Asset Management','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('RC Holdco','Asset Management','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('RC Holdco','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('RC Holdco','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('RC Holdco','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('RC Holdco','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('RC Holdco','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Rockefeller Center','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Rockefeller Center','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Rockefeller Center','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Rockefeller Center','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Rockefeller Center','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Tishman Speyer Tenant Services Inc','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Tishman Speyer Tenant Services Inc','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS 200 Park VI LP','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS 200 Park VI LP','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS 200 Park VI LP','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS 200 Park VI LP','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS 200 Park VI LP','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS 400 South Hope VI LLC','Leasing','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS 400 South Hope VI LLC','Property Management CapEx','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS 400 South Hope VI LLC','Property Management CapEx','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS 400 South Hope VI LLC','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS 400 South Hope VI LLC','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS 400 South Hope VI LLC','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS 400 South Hope VI LLC','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Participants','Acquisitions','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Participants','Asset Management','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Participants','Fund Organization','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Participants','Fund Operations','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Participants','Syndication (Investment and Fund)','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Participants','Acquisitions','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Participants','Asset Management','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Participants','Fund Organization','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Participants','Fund Operations','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Participants','Syndication (Investment and Fund)','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Unitholders','Acquisitions','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Unitholders','Asset Management','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Unitholders','Fund Organization','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Unitholders','Fund Operations','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Unitholders','Syndication (Investment and Fund)','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Unitholders','Acquisitions','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Unitholders','Asset Management','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Unitholders','Fund Organization','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Unitholders','Fund Operations','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TS Unitholders','Syndication (Investment and Fund)','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSAL','Acquisitions','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSAL','Asset Management','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSAL','Fund Organization','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSAL','Fund Operations','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSAL','Syndication (Investment and Fund)','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSAL','Acquisitions','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSAL','Asset Management','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSAL','Fund Organization','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSAL','Fund Operations','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSAL','Syndication (Investment and Fund)','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSCE - China RMB Fund','Asset Management','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSCE - China RMB Fund','Asset Management','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP - PCVST Fund','Asset Management','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP - PCVST Fund','Asset Management','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP 125 South Wacker','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP 125 South Wacker','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP 222 North Lasalle','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP 222 North Lasalle','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP Bayside Towers','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP Bayside Towers','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP Bayside Towers','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP Bayside Towers','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP Brazil Fund II','Acquisitions','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP Brazil Fund II','Acquisitions','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP Lehman Data Center','Development','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP Lehman Data Center','Development','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP Miami','CORP','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP Miami','CORP','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP TSEC','Asset Management','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP TSEC','Asset Management','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP TSEV','Asset Management','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TSP TSEV','Asset Management','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TST 1071 Holding, LLC','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TST 1071 Holding, LLC','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TST 1071 Holding, LLC','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('TST 1071 Holding, LLC','Property Management Non-Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Wellington','Development','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Wellington','Development','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Woodland Park Property','Development','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Woodland Park Property','Development','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Woodland Park Property','Property Management Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Woodland Park Property','Property Management Escalatable','Payroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Woodland Park Property','Property Management Non-Escalatable','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Yankees','Development','NonPayroll')
Insert Into AdditionalValidCombinationsForEntityActivity (ReportingEntityName,ActivityTypeName,AllocationTypeName)VALUES('Yankees','Development','Payroll')
