/*

--Done by ACT

USE BR_CORP
GO
ALTER TABLE JOURNAL ALTER COLUMN DESCRPN NCHAR(60) NULL
ALTER TABLE importjournal ALTER COLUMN DESCRPN NCHAR(60) NULL

USE BR_PROP
GO
ALTER TABLE JOURNAL ALTER COLUMN DESCRPN NCHAR(60) NULL
ALTER TABLE importjournal ALTER COLUMN DESCRPN NCHAR(60) NULL
GO
*/