USE MRIOB
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GACC' AND COLUMN_NAME = 'ISGR')
	BEGIN
	ALTER TABLE GACC ADD ISGR CHAR(1)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GHIS' AND COLUMN_NAME = 'CDEP' and CHARACTER_MAXIMUM_LENGTH = '6')
	BEGIN
	ALTER TABLE GHIS ADD CDEP CHAR(6)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'JOURNAL' AND COLUMN_NAME = 'CDEP' and CHARACTER_MAXIMUM_LENGTH = '6')
	BEGIN
	ALTER TABLE JOURNAL ADD CDEP CHAR(6)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'JOURNAL' AND COLUMN_NAME = 'DESCRPN' and CHARACTER_MAXIMUM_LENGTH = '60')
	BEGIN
	ALTER TABLE JOURNAL ALTER COLUMN DESCRPN Char(60)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GHIS' AND COLUMN_NAME = 'DESCRPN' and CHARACTER_MAXIMUM_LENGTH = '60')
	BEGIN
	ALTER TABLE GHIS ALTER COLUMN DESCRPN Char(60)
	END
GO

USE EU_COB
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GACC' AND COLUMN_NAME = 'ISGR')
	BEGIN
	ALTER TABLE GACC ADD ISGR CHAR(1)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GHIS' AND COLUMN_NAME = 'CDEP' and CHARACTER_MAXIMUM_LENGTH = '6')
	BEGIN
	ALTER TABLE GHIS ADD CDEP CHAR(6)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'JOURNAL' AND COLUMN_NAME = 'CDEP' and CHARACTER_MAXIMUM_LENGTH = '6')
	BEGIN
	ALTER TABLE JOURNAL ADD CDEP CHAR(6)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'JOURNAL' AND COLUMN_NAME = 'DESCRPN' and CHARACTER_MAXIMUM_LENGTH = '60')
	BEGIN
	ALTER TABLE JOURNAL ALTER COLUMN DESCRPN Char(60)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GHIS' AND COLUMN_NAME = 'DESCRPN' and CHARACTER_MAXIMUM_LENGTH = '60')
	BEGIN
	ALTER TABLE GHIS ALTER COLUMN DESCRPN Char(60)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GDEP' AND COLUMN_NAME = 'NETTSCOST' and CHARACTER_MAXIMUM_LENGTH = '1')
	BEGIN
	ALTER TABLE GDEP ADD NETTSCOST Char(1)
	END
GO

USE CDT_PROP
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GACC' AND COLUMN_NAME = 'ISGR')
	BEGIN
	ALTER TABLE GACC ADD ISGR CHAR(1)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GHIS' AND COLUMN_NAME = 'CDEP' and CHARACTER_MAXIMUM_LENGTH = '6')
	BEGIN
	ALTER TABLE GHIS ADD CDEP CHAR(6)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'JOURNAL' AND COLUMN_NAME = 'CDEP' and CHARACTER_MAXIMUM_LENGTH = '6')
	BEGIN
	ALTER TABLE JOURNAL ADD CDEP CHAR(6)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'JOURNAL' AND COLUMN_NAME = 'DESCRPN' and CHARACTER_MAXIMUM_LENGTH = '60')
	BEGIN
	ALTER TABLE JOURNAL ALTER COLUMN DESCRPN Char(60)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GHIS' AND COLUMN_NAME = 'DESCRPN' and CHARACTER_MAXIMUM_LENGTH = '60')
	BEGIN
	ALTER TABLE GHIS ALTER COLUMN DESCRPN Char(60)
	END
GO

--ALTER TABLE GHIS2 ALTER COLUMN DESCRPN Char(60)
GO

GO

USE CDT_CORP
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GACC' AND COLUMN_NAME = 'ISGR')
	BEGIN
	ALTER TABLE GACC ADD ISGR CHAR(1)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GHIS' AND COLUMN_NAME = 'CDEP' and CHARACTER_MAXIMUM_LENGTH = '6')
	BEGIN
	ALTER TABLE GHIS ADD CDEP CHAR(6)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'JOURNAL' AND COLUMN_NAME = 'CDEP' and CHARACTER_MAXIMUM_LENGTH = '6')
	BEGIN
	ALTER TABLE JOURNAL ADD CDEP CHAR(6)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'JOURNAL' AND COLUMN_NAME = 'DESCRPN' and CHARACTER_MAXIMUM_LENGTH = '60')
	BEGIN
	ALTER TABLE JOURNAL ALTER COLUMN DESCRPN Char(60)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GHIS' AND COLUMN_NAME = 'DESCRPN' and CHARACTER_MAXIMUM_LENGTH = '60')
	BEGIN
	ALTER TABLE GHIS ALTER COLUMN DESCRPN Char(60)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GDEP' AND COLUMN_NAME = 'NETTSCOST' and CHARACTER_MAXIMUM_LENGTH = '1')
	BEGIN
	ALTER TABLE GDEP ADD NETTSCOST Char(1)
	END
GO


USE BR_PROP
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GACC' AND COLUMN_NAME = 'ISGR')
	BEGIN
	ALTER TABLE GACC ADD ISGR CHAR(1)
	END
GO
--IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GHIS' AND COLUMN_NAME = 'CDEP' and CHARACTER_MAXIMUM_LENGTH = '6')
--	BEGIN
--	ALTER TABLE GHIS ADD CDEP CHAR(6)
--	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'JOURNAL' AND COLUMN_NAME = 'CDEP' and CHARACTER_MAXIMUM_LENGTH = '6')
	BEGIN
	ALTER TABLE JOURNAL ADD CDEP CHAR(6)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'JOURNAL' AND COLUMN_NAME = 'DESCRPN' and CHARACTER_MAXIMUM_LENGTH = '60')
	BEGIN
	ALTER TABLE JOURNAL ALTER COLUMN DESCRPN Char(60)
	END
GO
--IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GHIS' AND COLUMN_NAME = 'DESCRPN' and CHARACTER_MAXIMUM_LENGTH = '60')
--	BEGIN
--	ALTER TABLE GHIS ALTER COLUMN DESCRPN Char(60)
--	END
GO
--ALTER TABLE GHIS ALTER COLUMN DESCRPN Char(60)
GO


USE BR_CORP
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GACC' AND COLUMN_NAME = 'ISGR')
	BEGIN
	ALTER TABLE GACC ADD ISGR CHAR(1)
	END
GO
--IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GHIS' AND COLUMN_NAME = 'CDEP' and CHARACTER_MAXIMUM_LENGTH = '6')
--	BEGIN
--	ALTER TABLE GHIS ADD CDEP CHAR(6)
--	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'JOURNAL' AND COLUMN_NAME = 'CDEP' and CHARACTER_MAXIMUM_LENGTH = '6')
	BEGIN
	ALTER TABLE JOURNAL ADD CDEP CHAR(6)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'JOURNAL' AND COLUMN_NAME = 'DESCRPN' and CHARACTER_MAXIMUM_LENGTH = '60')
	BEGIN
	ALTER TABLE JOURNAL ALTER COLUMN DESCRPN Char(60)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GDEP' AND COLUMN_NAME = 'NETTSCOST' and CHARACTER_MAXIMUM_LENGTH = '1')
	BEGIN
	ALTER TABLE GDEP ADD NETTSCOST Char(1)
	END
GO


USE IN_PROP
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GACC' AND COLUMN_NAME = 'ISGR')
	BEGIN
	ALTER TABLE GACC ADD ISGR CHAR(1)
	END
GO
--IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GHIS' AND COLUMN_NAME = 'CDEP' and CHARACTER_MAXIMUM_LENGTH = '6')
--	BEGIN
--	ALTER TABLE GHIS ADD CDEP CHAR(6)
--	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'JOURNAL' AND COLUMN_NAME = 'CDEP' and CHARACTER_MAXIMUM_LENGTH = '6')
	BEGIN
	ALTER TABLE JOURNAL ADD CDEP CHAR(6)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'JOURNAL' AND COLUMN_NAME = 'DESCRPN' and CHARACTER_MAXIMUM_LENGTH = '60')
	BEGIN
	ALTER TABLE JOURNAL ALTER COLUMN DESCRPN Char(60)
	END
GO


USE IN_CORP
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GACC' AND COLUMN_NAME = 'ISGR')
	BEGIN
	ALTER TABLE GACC ADD ISGR CHAR(1)
	END
GO
--IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GHIS' AND COLUMN_NAME = 'CDEP' and CHARACTER_MAXIMUM_LENGTH = '6')
--	BEGIN
--	ALTER TABLE GHIS ADD CDEP CHAR(6)
--	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'JOURNAL' AND COLUMN_NAME = 'CDEP' and CHARACTER_MAXIMUM_LENGTH = '6')
	BEGIN
	ALTER TABLE JOURNAL ADD CDEP CHAR(6)
	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'JOURNAL' AND COLUMN_NAME = 'DESCRPN' and CHARACTER_MAXIMUM_LENGTH = '60')
	BEGIN
	ALTER TABLE JOURNAL ALTER COLUMN DESCRPN Char(60)
	END
GO
--IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GHIS' AND COLUMN_NAME = 'DESCRPN' and CHARACTER_MAXIMUM_LENGTH = '60')
--	BEGIN
--	ALTER TABLE GHIS ALTER COLUMN DESCRPN Char(60)
--	END
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GDEP' AND COLUMN_NAME = 'NETTSCOST' and CHARACTER_MAXIMUM_LENGTH = '1')
	BEGIN
	ALTER TABLE GDEP ADD NETTSCOST Char(1)
	END
GO


GO

USE China_CORP
GO
IF NOT EXISTS(Select * From INFORMATION_SCHEMA.COLUMNS Where TABLE_NAME = 'GDEP' AND COLUMN_NAME = 'NETTSCOST' and CHARACTER_MAXIMUM_LENGTH = '1')
	BEGIN
	ALTER TABLE GDEP ADD NETTSCOST Char(1)
	END
GO