IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE COLUMN_NAME = 'FeeOrExpenseMultiplicationFactor' AND TABLE_NAME = 'GlAccountCategory')
BEGIN

	SET QUOTED_IDENTIFIER ON
	SET ARITHABORT ON
	SET NUMERIC_ROUNDABORT OFF
	SET CONCAT_NULL_YIELDS_NULL ON
	SET ANSI_NULLS ON
	SET ANSI_PADDING ON
	SET ANSI_WARNINGS ON

	ALTER TABLE dbo.GlAccountCategory
		DROP COLUMN FeeOrExpenseMultiplicationFactor

	ALTER TABLE dbo.GlAccountCategory SET (LOCK_ESCALATION = TABLE)

END